server:
  port: 8081

broker:
   username: admin
   password: admin217
   queuename: taskQueue
   host: localhost
   port: 5672

database:
   username: admin
   password: admin345
   host: localhost
   port: 3306