server:
  port: 8081

broker:
   username: admin
   password: admin217
   queuename: taskQueue
   host: localhost
   port: 5672

database:
   username: root
   password: root4db
   host: localhost
   port: 3306
   driver: mysql
   database: task
   migrationPath: migrations