basePath: /
definitions:
  model.HealthResponse:
    properties:
      message:
        type: string
    type: object
  model.TaskRequest:
    properties:
      taskName:
        type: string
    type: object
  model.TaskResponse:
    properties:
      taskId:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: abondar24@yahoo.com
    name: Alex
  description: Task API to send commands as tasks
  license:
    name: MIT
  termsOfService: http://swagger.io/terms/
  title: Task API
  version: "1.0"
paths:
  /health:
    get:
      description: Checks if service is up
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.HealthResponse'
      summary: Health of service
      tags:
      - tasks
  /task/create:
    post:
      consumes:
      - application/json
      description: Create a new task and send it to the queue
      parameters:
      - description: Create Task
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/model.TaskRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.TaskResponse'
      summary: Create a new task
      tags:
      - tasks
  /task/delete:
    delete:
      description: Delete existing task
      parameters:
      - description: Delete Task
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Delete task
      tags:
      - tasks
  /task/update:
    put:
      description: Change status of existing task
      parameters:
      - description: Update Task
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Update task
      tags:
      - tasks
swagger: "2.0"
