basePath: /
definitions:
  model.TaskRequest:
    properties:
      taskName:
        type: string
    type: object
  model.TaskResponse:
    properties:
      taskId:
        type: string
    type: object
  response.ErrorResponse:
    properties:
      error:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: abondar24@yahoo.com
    name: Alex
  description: Task API to send commands as tasks
  license:
    name: MIT
  termsOfService: http://swagger.io/terms/
  title: Task API
  version: "1.0"
paths:
  /task:
    post:
      consumes:
      - application/json
      description: Create a new task and send it to the queue
      parameters:
      - description: Task name
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/model.TaskRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.TaskResponse'
        "502":
          description: Failed to send command
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Create a new task
      tags:
      - tasks
  /task/{id}:
    delete:
      description: Delete existing task
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "400":
          description: Missing id param
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "502":
          description: Failed to send command
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Delete task
      tags:
      - tasks
    put:
      description: Change status of existing task
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: string
      - description: 'Complete task. Possible values: true/false'
        in: query
        name: complete
        required: true
        type: string
      produces:
      - application/json
      responses:
        "400":
          description: Missing id or completed param
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "502":
          description: Failed to send command
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Update task
      tags:
      - tasks
swagger: "2.0"
